sudo: required
servies:
 - docker

before_install:
 - docker build -t zetajonathan/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true zetajonathan/react-test npm test -- --coverage

after_success:
 - docker build -t zetajonathan/multi-client ./client
 - docker build -t zetajonathan/multi-nginx ./nginx
 - docker build -t zetajonathan/multi-server ./server
 - docker build -t zetajonathan/multi-worker ./worker
 # Log in to the docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 # Take the images and push them to ducker hub
 - docker push zetajonathan/multi-client
 - docker push zetajonathan/multi-nginx
 - docker push zetajonathan/multi-server
 - docker push zetajonathan/multi-worker

deploy:
 provider: elasticbeanstalk
 region: eu-west-1
 app: multi-docker
 env: MultiDocker-env
 bucket_name: elasticbeanstalk-eu-west-1-219942322862
 bucket_path: docker-multi
 on:
  branch: master
 acces_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY